services:
  puppeteer-service:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - dokploy-network
    shm_size: 1gb
    # Setting traefik.enable=false prevents Traefik from exposing this service
    labels:
      - traefik.enable=true
networks:
  dokploy-network:
    external: true
